### ISSUE TITLE
The site is inaccessible (expired certificate)

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub.org#8]
<img width="837" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/126963012-6830218f-6bf5-4749-b833-0715ba1f00df.png">

Should the DNS be fixed? If the names servers support CNAME flattening, I think it's best to set `npmhub.github.io`

**Comment by zeke** [comment]
Hey thanks for the ping. I'm not seeing that the site is down, but I am seeing this error at https://github.com/npmhub/npmhub.org/settings/pages

DNS has been configured with an ALIAS for all these years. Nothing has changed in terms of registration or the DNS config on my side. I guess maybe there's a new requirement on GitHub's side. I can add a CNAME and let's see if that helps.

**Comment by zeke** [comment]
Okay I deleted the ALIAS record and attempted to add a CNAME in dnsimple.com without specifying a subdomain but I got this error:

![Screen Shot 2021-07-27 at 5 30 23 PM](https://user-images.githubusercontent.com/2289/127244700-0981f9e0-eed8-4d79-8a15-e43d320758e8.png)


Which is weird because I don't see any other records for `npmhub.org`. I went ahead and added the CNAME for `*.npmhub.org`... not sure if that will work though:

![Screen Shot 2021-07-27 at 5 32 31 PM](https://user-images.githubusercontent.com/2289/127244762-66760c65-a1ee-45cc-8f3b-ba8ce47d256b.png)

**Comment by fregante** [comment]
Technically CNAMEs can only be set on subdomains, so that's why it's not letting you leave it empty. I think you will have to use ALIAS to set the root domain, which is what DNSimple calls the "CNAME flattening" I was talking about: https://support.dnsimple.com/articles/common-dns-records/#1-root-domain-examplecom

More info on: https://support.dnsimple.com/articles/alias-record/

**Comment by fregante** [comment]
Yesterday the SSL was failing, now the root domain doesn't resolve:

<img width="412" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/127265795-10d823ed-7890-40b3-8028-82ced82c9b6c.png">

**Comment by zeke** [comment]
Okay I've re-added the ALIAS record as it was before. That should restore the site.

![Screen Shot 2021-07-28 at 11 46 00 AM](https://user-images.githubusercontent.com/2289/127378809-e89f2c62-ba47-447e-8434-fe2ceb4d2567.png)

I'll ping some GitHub Pages folks to see if I can figure out what the issue is.

**Comment by fregante** [comment]
It looks like the host is resolving and the certificate is now valid 👍 

https://www.ssllabs.com/ssltest/analyze.html?d=npmhub.org&latest

Is it possible that the previous ALIAS pointed to npm-hub or other previous variations?

**Comment by zeke** [comment]
Looks like turning it off and on again did the trick. 🤷🏼
